apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: bmfi1fq0s-go 
  janus-idp.io/tekton: bmfi1fq0s-go
  backstage.io/kubernetes-id: bmfi1fq0s-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: bmfi1fq0s-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  