apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: bmfi1fq0s-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:d9ae3d01451adf5557cb87b9839ac732a518e89b@sha256:2aff0f8165dfac0574f9a3963a0bb0e8feba45914360dc4a0d91a7387966a717
          name: container-image
